Nginx:
  environment:
    VIRTUAL_HOST: static.b0tchsec.com
    GENERATE_SERVER_BLOCK: 'true'
    CERT_NAME: static_b0tchsec_com
  external_links:
  - TechnoWizardry/Piwik:piwik
  cap_drop:
  - ALL
  log_driver: ''
  labels:
    io.rancher.container.pull_image: always
  log_opt: {}
  image: b0tchsec/static.b0tchsec.com
  volumes:
  - /home/b0tchsec/website_content:/var/www:ro
  net: bridge
  mem_limit: 67108864
  cap_add:
  - CHOWN
  - DAC_OVERRIDE
  - NET_BIND_SERVICE
  - SETGID
  - SETUID
